services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppds-container
    volumes:
      - .:/var/www/html
    networks:
      - app-bridge

  webserver:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf   # Menyambungkan file konfigurasi Nginx
    depends_on:
      - app   # Nginx harus menunggu app (PHP-FPM) siap
    networks:
      - app-bridge

  npm:
    image: node:20.17.0
    container_name: node-container
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
      - ./npm/logs:/root/.npm/_logs/
    working_dir: /var/www/html
    command: npm run dev
    depends_on:
      - app   # Nginx harus menunggu app (PHP-FPM) siap
    networks:
      - app-bridge

networks:
  app-bridge:
    external: true